// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_LabelHeartRate = NULL;
lv_obj_t * ui_LabelSpO2 = NULL;
lv_obj_t * ui_LabelSteps = NULL;
lv_obj_t * ui_LabelHours = NULL;
lv_obj_t * ui_LabelMinutes = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_ArcSpO2 = NULL;
lv_obj_t * ui_ArcHeartRate = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_384128403, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 172);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 87);
    lv_obj_set_y(ui_Panel1, -85);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 172);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 89);
    lv_obj_set_y(ui_Panel2, 96);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 172);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 87);
    lv_obj_set_y(ui_Panel3, 36);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 172);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 87);
    lv_obj_set_y(ui_Panel4, -23);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeartRate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHeartRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeartRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeartRate, 17);
    lv_obj_set_y(ui_LabelHeartRate, 38);
    lv_obj_set_align(ui_LabelHeartRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeartRate, "68 bpm");

    ui_LabelSpO2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSpO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpO2, 11);
    lv_obj_set_y(ui_LabelSpO2, 61);
    lv_obj_set_align(ui_LabelSpO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpO2, "99.2% ");
    lv_obj_set_style_text_font(ui_LabelSpO2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSteps = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSteps, 19);
    lv_obj_set_y(ui_LabelSteps, 86);
    lv_obj_set_align(ui_LabelSteps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSteps, "42 steps");
    lv_obj_set_style_text_font(ui_LabelSteps, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHours = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHours, 3);
    lv_obj_set_y(ui_LabelHours, -46);
    lv_obj_set_align(ui_LabelHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHours, "12");
    lv_obj_set_style_text_font(ui_LabelHours, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinutes = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelMinutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinutes, 5);
    lv_obj_set_y(ui_LabelMinutes, -10);
    lv_obj_set_align(ui_LabelMinutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinutes, "34");
    lv_obj_set_style_text_font(ui_LabelMinutes, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_1608389725);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Image4, -33);
    lv_obj_set_y(ui_Image4, 59);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_heart_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image5, -32);
    lv_obj_set_y(ui_Image5, 37);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 235);

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_2029598083);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image7, -33);
    lv_obj_set_y(ui_Image7, 86);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image7, 240);

    ui_ArcSpO2 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcSpO2, 250);
    lv_obj_set_height(ui_ArcSpO2, 225);
    lv_obj_set_x(ui_ArcSpO2, 13);
    lv_obj_set_y(ui_ArcSpO2, 1);
    lv_obj_set_align(ui_ArcSpO2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcSpO2, 50);
    lv_obj_set_style_blend_mode(ui_ArcSpO2, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ArcSpO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcSpO2, lv_color_hex(0xF6F2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpO2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSpO2, lv_color_hex(0x68539F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpO2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpO2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSpO2, lv_color_hex(0x6A509C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSpO2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcHeartRate = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcHeartRate, 199);
    lv_obj_set_height(ui_ArcHeartRate, 215);
    lv_obj_set_x(ui_ArcHeartRate, 0);
    lv_obj_set_y(ui_ArcHeartRate, 9);
    lv_obj_set_align(ui_ArcHeartRate, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcHeartRate, 0, 140);
    lv_arc_set_value(ui_ArcHeartRate, 50);
    lv_obj_set_style_blend_mode(ui_ArcHeartRate, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ArcHeartRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcHeartRate, lv_color_hex(0xF6F2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHeartRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHeartRate, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHeartRate, lv_color_hex(0xEE1C18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHeartRate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHeartRate, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHeartRate, lv_color_hex(0xEE1810), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHeartRate, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_LabelHeartRate = NULL;
    ui_LabelSpO2 = NULL;
    ui_LabelSteps = NULL;
    ui_LabelHours = NULL;
    ui_LabelMinutes = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image7 = NULL;
    ui_ArcSpO2 = NULL;
    ui_ArcHeartRate = NULL;

}
